# This is an entry point of the deployment
# General recommendation to use single file that describes what steps should be executed in parallel
# and what in a sequence. Each step should be represented as a separate file.
version: 1.0.0
station:
  name: a6s.sequence
  resolvers:
    '':
      name: 'a6s.context'
      options_file: options.yml

  options:
    - name: a6s.external
      options:
        file: 0-common.yml

    - name: a6s.external
      options:
        file: 1-services.yml

#    - name: a6s.external
#      options:
#        file: 2-cleanup.yml